; PlatformIO Project Configuration File for EXP-03 Distributed Multi-MCU Communication Lab
;
; Node Targets:
; - esp32_master: ESP32 DevKit V1 (30 pins) Master Gateway & Coordinator
; - stm32_coprocessor: STM32F4 Black Pill (STM32F401CC) Math & Stepper Motor Coprocessor
; - nano_subcontroller: Arduino Nano (ATmega328P, 5V) I/O Expander & Sub-Controller
; - wokwi: Wokwi Simulator dual-target environment for ESP32

[platformio]
default_envs = esp32_master

[env:esp32_master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<master/*>
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DESP32_MASTER_NODE
lib_deps =
    ; Thư viện phục vụ Web & WebSocket chuẩn
    links2004/WebSockets @ ^2.4.1

[env:stm32_coprocessor]
platform = ststm32
board = blackpill_f401cc
framework = arduino
monitor_speed = 115200
build_src_filter = +<coprocessor/*>
build_flags =
    -DSTM32_COPROCESSOR_NODE

[env:nano_subcontroller]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 115200
build_src_filter = +<subcontroller/*>
build_flags =
    -DNANO_SUBCONTROLLER_NODE

[env:wokwi]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<master/*>
build_flags =
    -DWOKWI_SIMULATION
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    links2004/WebSockets @ ^2.4.1
