[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    miguelbalboa/MFRC522@^1.4.11
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/RTClib@^2.1.3
    madhephaestus/ESP32Servo@^3.0.5
    chris--a/Keypad@^3.1.1
    bblanchon/ArduinoJson@^7.0.0
    SPI
    Wire
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DMFRC522_SPICLOCK=1000000u

[env:wokwi]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    miguelbalboa/MFRC522@^1.4.11
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/RTClib@^2.1.3
    madhephaestus/ESP32Servo@^3.0.5
    chris--a/Keypad@^3.1.1
    bblanchon/ArduinoJson@^7.0.0
    SPI
    Wire
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DWOKWI_SIMULATION
    -DMFRC522_SPICLOCK=1000000u
