[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	arminjo/Talkie @ ^1.4.0
	https://github.com/avishorp/TM1637.git
	chris--a/Keypad @ ^3.1.1
build_flags = 
	-DCORE_DEBUG_LEVEL=0

[env:wokwi]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	arminjo/Talkie @ ^1.4.0
	https://github.com/avishorp/TM1637.git
	chris--a/Keypad @ ^3.1.1
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DWOKWI_SIMULATION
